version: '3.7'
services:
  face-fusion:
    build:
      context: .
      dockerfile: Dockerfile
    image: xuan1918/facefusion:v0.1.1
    container_name: face_fusion
    privileged: true
    ports:
      - "6009:6009"
    environment:
        - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /home/xuan/Projects/data/:/opt/data/

#docker-compose build --build-arg GITHUB_PAT="$(cat ~/.ssh/github_xuan_desktop_token)"