version: '3.7'
services:
  face-fusion:
    build:
      context: .
      dockerfile: Dockerfile
    image: xuan1918/facefusion:v0.0.1
    environment:
        - NVIDIA_VISIBLE_DEVICES=all
    env_file:
      - face_fusion.env
    volumes:
      - /home/xuan/Projects/data/face_fuse:/opt/data/

#docker-compose build --build-arg SSH_PRV_KEY="$(cat ~/.ssh/id_rsa_github_deploy)" --build-arg SSH_PUB_KEY="$(cat ~/.ssh/id_rsa_github_deploy.pub)"